## NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2) # Return evenly spaced values within a given interval.

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.linspace(0,5,10) # one dimensional vector noted by one set of 10 evenly spaced points from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.random.rand(5)

array([0.61225781, 0.5217017 , 0.45680117, 0.93159747, 0.92258464])

In [17]:
np.random.rand(5,5)  # uniform distribution

array([[0.79729583, 0.89298287, 0.45081115, 0.59305282, 0.41031478],
       [0.67661208, 0.04641776, 0.6859594 , 0.74624666, 0.59710735],
       [0.68825688, 0.12844293, 0.43464539, 0.8589543 , 0.49844661],
       [0.10144573, 0.96062638, 0.00605732, 0.74845576, 0.71080769],
       [0.92591326, 0.35144471, 0.05463611, 0.90244579, 0.07228221]])

In [18]:
np.random.randn(2) #standard normal distribution

array([ 1.84471597, -0.42691303])

In [20]:
np.random.randint(1, 100, 10)

array([81, 22, 46,  4, 67, 21, 26, 93,  6, 63])

In [21]:
arr = np.arange(25)  # one dimensional array of 25 numbers

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([46, 12, 46, 32, 23, 18, 24,  6, 21, 33])

In [33]:
arr.reshape(5,5) #reshape it as a 5 x 5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr.max()

46

In [35]:
ranarr.min()

6

In [36]:
ranarr.argmax()

0

In [31]:
ranarr.argmin()

7

In [37]:
arr.shape

(25,)

In [38]:
arr.dtype

dtype('int32')

In [39]:
from numpy.random import randint
randint(2,10)

5

## Numpy Indexing and Selection

In [40]:
import numpy as np

In [41]:
arr = np.arange(0, 11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [47]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[0:5]=100

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr=arr[0:6]

In [53]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:]=99

In [55]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [60]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[0][0]

5

In [64]:
arr_2d[1][2]

30

In [63]:
arr_2d[1,2] # first row, second column

30

In [65]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
#Grab the first row
arr_2d[0, None, :]

array([[ 5, 10, 15]])

In [72]:
#Grab the second row
arr_2d[1,None,:]

array([[20, 25, 30]])

In [73]:
#Grab the third row
arr_2d[2,None,:]

array([[35, 40, 45]])

In [76]:
#Grab the first column
arr_2d[:,0,None]

array([[ 5],
       [20],
       [35]])

In [77]:
#Grab the second column
arr_2d[:,1,None]

array([[10],
       [25],
       [40]])

In [78]:
#Grab the third column
arr_2d[:,2,None]

array([[15],
       [30],
       [45]])

In [81]:
arr=np.arange(1,11)

In [82]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [85]:
bool_arr = arr > 5

In [86]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [87]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [88]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [89]:
arr[arr<3]

array([1, 2])

In [90]:
arr_2d = np.arange(50).reshape(5,10)

In [91]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [92]:
arr_2d[1:3,3:5] # grabbing the second, third row and fourth and fifth column(index 3 and 4)

array([[13, 14],
       [23, 24]])

In [93]:
arr_2d[1:3] # grabbing the second and third row

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## NumPy Operations

In [94]:
import numpy as np

In [96]:
arr = np.arange(0,11)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [102]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [103]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [104]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [106]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [107]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [108]:
np.max(arr)

10

In [109]:
np.min(arr)

0

In [110]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [111]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [112]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])